// Inlined from packages/shared-types/src/sketch.ts at template-prep time.
// Edit the source file in the monorepo and re-run template-prep, NOT this file.


export interface SketchPhoto {
  src: string;
  alt: string;
}

export interface SketchBranding {
  logoUrl: string | null;
  themeColor: string;
  themeColorAccent: string | null;
  businessName: string;
  tagline: string | null;
}

export interface SketchContent {
  branding: SketchBranding;
  hero: {
    headline: string;
    subheadline: string;
    ctaText: string;
    image: SketchPhoto | null;
  };
  about: {
    title: string;
    body: string;
    image: SketchPhoto | null;
  };
  services: Array<{ title: string; description: string; icon?: string }>;
  gallery: SketchPhoto[];
  testimonials?: Array<{ name: string; quote: string; rating?: number }>;
  /**
   * Optional FAQ items — when present, the layout renders an accordion
   * section. Generated by an AI agent from the about + services + caption
   * analysis. Keep concise: 4-7 items, 1-3 sentence answers.
   */
  faq?: Array<{ question: string; answer: string }>;
  /**
   * Optional process timeline — "how working with us looks step by step".
   * Mostly relevant for service-providers (doula, photographer, lawyer).
   * 3-5 steps, each with a short label + description.
   */
  processSteps?: Array<{ title: string; description: string }>;
  /**
   * Trust signals — real numbers from public sources (Google, Instagram, FB,
   * TikTok). Rendered as a small strip on the hero or below it. We never
   * fabricate; if a number is missing we just don't show it.
   */
  trust?: {
    googleRating?: number; // 0-5 (decimal, average of reviews)
    googleReviewCount?: number;
    instagramFollowers?: number;
    facebookFollowers?: number;
    tiktokFollowers?: number;
    /** Total cross-platform reach for a single "X followers" badge */
    totalFollowers?: number;
  };
  /**
   * Optional list of section keys the customer chose to include. When set,
   * layouts only render sections whose key appears here. When undefined,
   * all sections render (backward compat for sketches generated before
   * this feature). Hero is always rendered regardless.
   *
   * Keys come from `DOULA_OPTIONAL_SECTIONS` (and equivalents per archetype):
   * 'about' | 'services' | 'process' | 'gallery' | 'testimonials' | 'faq'
   * | 'map' | 'contact'
   */
  selectedSections?: string[];
  contact: {
    phone?: string;
    email?: string;
    whatsappNumber?: string;
    address?: string;
    workingHours?: string;
    mapEmbed?: string;
    instagramHandle?: string;
  };
  seo: {
    title: string;
    description: string;
    keywords: string[];
  };
}

export interface Sketch {
  id: string;
  leadId: string;
  templateId: string;
  content: SketchContent;
  previewUrl: string;
  previewScreenshotsUrls: string[];
  approvalStatus: string;
  rejectionReason: string | null;
  createdAt: Date;
  updatedAt: Date;
}
